### PR TITLE
Resolves part of #84

### PR DESCRIPTION
**Pull request by AstroOrbis**
Will continue Discord caches soon because of the many paths: Discord, Discord PTB, Discord Canary, Discord Development, etc.

### CODE REVIEW

**Comment by AstroOrbis** [comment]
Time to update README.MD!

**Comment by AstroOrbis** [comment]
Done :3

**Comment by AstroOrbis** [comment]
Eyyy pog! Thanks :3

**Comment by fwartner** [comment]
Also in addition to that, a new release has been created!

https://twitter.com/fwartner/status/1417895040890798081

Thank you!

**Comment by AstroOrbis** [comment]
Big poggers! Looking forward to contributing more ^W^

**Comment by AstroOrbis** [comment]
(yes this is foreshadowing)

**Comment by fwartner** [comment]
Contributions are always welcome!

I probably do a re-write of this soon.

Also, if you like this tool and it helps you throughout the day, consider sponsor my work :)

**Comment by AstroOrbis** [comment]
:)

**Pull request merged**
